# Nazwa aplikacji
spring.application.name=clinic-app

# Ustawienia bazy H2 (h2/mem(RAM)/clinicdb)
spring.datasource.url=jdbc:h2:file:./data/clinicdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatyczne tworzenie tabel ; stad baza wie ze tabela to tabela
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# Logowanie zapyta? SQL
spring.jpa.show-sql=true

# Konsola H2 !! uwaga nie dziala na razie - nie wiem czemu;
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ustawienie portu na localhost + address -> 0.0.0.0 po adresie ip mozliwosc odpalenia LAN(wi-fi)
server.port=8081
server.address=0.0.0.0

# HASLO ADMIN
app.admin-password=${APP_ADMIN_PASSWORD}